# Copyright 2025 "Google LLC"
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
apiVersion: apps/v1
kind: DaemonSet
metadata:
  labels:
    app: imex-installer
  name: imex-binary-installer
  namespace: kube-system
spec:
  selector:
    matchLabels:
      app: imex-installer
  template:
    metadata:
      labels:
        app: imex-installer
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-accelerator
                operator: In
                values:
                - "nvidia-gb200"
      tolerations:
      - operator: "Exists"
      hostPID: true
      containers:
      - name: imex-installer
        image: ubuntu:22.04
        securityContext:
          privileged: true
        command:
        - sh
        - -c
        - |
          set -e

          DRIVER_VERSION=$("/imex-bin/nvidia-smi" --query-gpu=driver_version --format=csv,noheader --id=0 2>&1)

          if [ -z "$DRIVER_VERSION" ]; then
            echo "Error: Could not retrieve NVIDIA driver version."
            exit 1
          fi

          echo "NVIDIA Driver Version: $DRIVER_VERSION"
          IMEX_DRIVER_VERSION=$(echo "$DRIVER_VERSION" | cut -d'.' -f1)
          TARGETARCH=arm64

          apt update
          apt install -y curl build-essential

          curl -fsSL -w "%{exitcode}\n" -o /imex-bin/nvidia-imex-${IMEX_DRIVER_VERSION}_${DRIVER_VERSION}-1_${TARGETARCH}.deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2204/sbsa/nvidia-imex-${IMEX_DRIVER_VERSION}_${DRIVER_VERSION}-1_${TARGETARCH}.deb

          dpkg -x /imex-bin/nvidia-imex-${IMEX_DRIVER_VERSION}_${DRIVER_VERSION}-1_${TARGETARCH}.deb /imex-bin/extract

          rm /imex-bin/nvidia-imex-${IMEX_DRIVER_VERSION}_${DRIVER_VERSION}-1_${TARGETARCH}.deb

          DEST_DIR="$IMEX_DEST_DIR"
          echo "Destination Dir: $DEST_DIR"
          echo "/imex-bin/extract found"
          echo "copying nvidia-imex to $DEST_DIR"
          cp /imex-bin/extract/usr/bin/nvidia-imex "$DEST_DIR"
          echo "copying nvidia-imex-ctl to $DEST_DIR"
          cp /imex-bin/extract/usr/bin/nvidia-imex-ctl "$DEST_DIR"
          echo "removing /imex-bin/extract"
          rm -r /imex-bin/extract
          echo "finished"
          tail -f /dev/null
        env:
        - name: IMEX_DEST_DIR
          value: /imex-bin
        - name: LD_LIBRARY_PATH
          value: /ld-lib
        volumeMounts:
        - name: imex-binaries
          mountPath: /imex-bin
        - name: ld-library
          mountPath: /ld-lib
    volumes:
    - name: imex-binaries
      hostPath:
        path: /home/kubernetes/bin/nvidia/bin
        type: Directory
    - name: ld-library
      hostPath:
        path: /home/kubernetes/bin/nvidia/lib64
        type: Directory
